kind: Secret
apiVersion: v1
data:
  db_password: {{ .Values.sanity_checks_pod.db_password | b64enc}}

metadata:
  name: sanity-checks-pod-secret
  namespace: {{ .Values.namespaces.application }}
type: Opaque
